In [2]:
import numpy as np
import tensorflow as tf

/home/ntapia/miniconda3/envs/idp/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
tf.reset_default_graph()
# labels
labels = np.array([
    [0,1,1,0],[1,0,0,0],[0,1,1,1],[1,0,1,0],[1,1,1,1],[1,1,1,1],[0,0,0,0]
])

print("labels shape",labels.shape)
depth = 2
labels_onehot = tf.one_hot(labels, depth)

logits = labels_onehot

loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels_onehot, logits=logits)
loss_prom =tf.reduce_mean(loss)

labels_single = tf.argmax(labels_onehot, axis=-1)

with tf.Session() as sess:
    #labels_onehot_np = sess.run(labels_onehot)
    out_np = sess.run(labels_single)
print(out_np)
print(out_np.shape)
print(labels)    

#print(labels_onehot_np)
#print(labels_onehot_np.shape)

labels shape (7, 4)
[[0 1 1 0]
 [1 0 0 0]
 [0 1 1 1]
 [1 0 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]
(7, 4)
[[0 1 1 0]
 [1 0 0 0]
 [0 1 1 1]
 [1 0 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]
