In [1]:
import numpy as np
import tensorflow as tf

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
tf.reset_default_graph()
# labels
labels = np.array([
    [0,1,1,0],[1,0,0,0],[0,1,1,1],[1,0,1,0],[1,1,1,1],[1,1,1,1],[0,0,0,0]
])

print("labels shape",labels.shape)
depth = 2
labels_onehot = tf.one_hot(labels, depth)

logits = labels_onehot

loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels_onehot, logits=logits)
loss_prom =tf.reduce_mean(loss)

labels_single = tf.argmax(labels_onehot, axis=-1)

with tf.Session() as sess:
    #labels_onehot_np = sess.run(labels_onehot)
    out_np = sess.run(labels_single)
print(out_np)
print(out_np.shape)
print(labels)    

#print(labels_onehot_np)
#print(labels_onehot_np.shape)

labels shape (7, 4)
[[0 1 1 0]
 [1 0 0 0]
 [0 1 1 1]
 [1 0 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]
(7, 4)
[[0 1 1 0]
 [1 0 0 0]
 [0 1 1 1]
 [1 0 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]


In [20]:
tf.reset_default_graph()
# labels of shape [batch, timesteps]
labels = np.array([
    [0,1,1,0],[1,0,0,0],[0,1,1,1],[1,0,1,0],[1,1,1,1],[1,1,1,1],[0,0,1,0]
])
print("labels shape",labels.shape)

# Fake logits of two classes, of shape [batch, timesteps, 2]
depth = 2
labels_onehot = tf.one_hot(labels, depth)
logits = labels_onehot

# Create weights
class_weights = tf.constant([0.1, 0.9])
weights = tf.gather(class_weights, labels)

loss_normal = tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels_onehot, logits=logits)
loss_normal_prom = tf.reduce_mean(loss_normal)
loss_sparse = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits, weights=weights)

with tf.Session() as sess:
    logits_np = sess.run(logits)
    loss_normal_np = sess.run(loss_normal)
    loss_normal_prom_np = sess.run(loss_normal_prom)
    loss_sparse_np = sess.run(loss_sparse)
    weights_np = sess.run(weights)
    
print("logits shape", logits_np.shape)
print("loss_normal", loss_normal_np.shape)
print("loss_normal_prom", loss_normal_prom_np.shape, loss_normal_prom_np)
print("loss_sparse", loss_sparse_np.shape, loss_sparse_np)
print("weights", weights_np)

print("labels", labels)

# Desired results:
print("loss", loss_normal_np)
print("weighted loss", weights_np*loss_normal_np, np.mean(weights_np*loss_normal_np))




labels shape (7, 4)
logits shape (7, 4, 2)
loss_normal (7, 4)
loss_normal_prom () 0.31326166
loss_sparse () 0.18348183
weights [[0.1 0.9 0.9 0.1]
 [0.9 0.1 0.1 0.1]
 [0.1 0.9 0.9 0.9]
 [0.9 0.1 0.9 0.1]
 [0.9 0.9 0.9 0.9]
 [0.9 0.9 0.9 0.9]
 [0.1 0.1 0.9 0.1]]
labels [[0 1 1 0]
 [1 0 0 0]
 [0 1 1 1]
 [1 0 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 1 0]]
loss [[0.31326163 0.31326163 0.31326163 0.31326163]
 [0.31326163 0.31326163 0.31326163 0.31326163]
 [0.31326163 0.31326163 0.31326163 0.31326163]
 [0.31326163 0.31326163 0.31326163 0.31326163]
 [0.31326163 0.31326163 0.31326163 0.31326163]
 [0.31326163 0.31326163 0.31326163 0.31326163]
 [0.31326166 0.31326166 0.31326166 0.31326166]]
weighted loss [[0.03132616 0.28193545 0.28193545 0.03132616]
 [0.28193545 0.03132616 0.03132616 0.03132616]
 [0.03132616 0.28193545 0.28193545 0.28193545]
 [0.28193545 0.03132616 0.28193545 0.03132616]
 [0.28193545 0.28193545 0.28193545 0.28193545]
 [0.28193545 0.28193545 0.28193545 0.28193545]
 [0.03132617 0.03132617